In [2]:
#numpy를 우리가 이용하기에 불편한 점이 있기에

In [4]:
#사람이 이용하기 편하게 ,wapping한 라이브러리

In [6]:
import pandas as pd

In [7]:
# 1차원과 2차원 데이터를 다루기 쉽게 만든 라이브러리

In [9]:
#용어를 잘 알아야 한다.
# 1차원데이터를 Series라고 한다.

In [12]:
production=pd.Series([450,480,465,490,470])  #1차원이지만 2차원 처럼 보임 , index(pandas)가 함께 나타남

In [13]:
production

0    450
1    480
2    465
3    490
4    470
dtype: int64

In [14]:
production.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
production.values

array([450, 480, 465, 490, 470])

In [17]:
production=pd.Series(data=[450,480,465,490,470],index=['월요일','화요일','수요일','목요일','금요일'])

In [20]:
production.values

array([450, 480, 465, 490, 470])

In [21]:
production.index

Index(['월요일', '화요일', '수요일', '목요일', '금요일'], dtype='object')

In [23]:
production.index.tolist() # series를 리스트로 만드는 법

['월요일', '화요일', '수요일', '목요일', '금요일']

In [24]:
production.size # size를 보는 법

5

In [25]:
production.ndim #차원보는법

1

In [27]:
production.shape #shape 보는 법

(5,)

In [28]:
production

월요일    450
화요일    480
수요일    465
목요일    490
금요일    470
dtype: int64

In [29]:
production['화요일']

np.int64(480)

In [34]:
production['화요일':'목요일'] #슬라이싱으로 데이터 가져오기

화요일    480
수요일    465
목요일    490
dtype: int64

In [35]:
production[['월요일','목요일']] #특정데이터만 가져오기

월요일    450
목요일    490
dtype: int64

In [36]:
production[production>=480] #boolean으로 데이터 가져오기

화요일    480
목요일    490
dtype: int64

In [39]:
production=production+10 #데이터 수정

In [40]:
production

월요일    470
화요일    500
수요일    485
목요일    510
금요일    490
dtype: int64

In [41]:
production['화요일']-=30

In [42]:
production

월요일    470
화요일    470
수요일    485
목요일    510
금요일    490
dtype: int64

In [43]:
production[['월요일','목요일','금요일']]+=20

In [44]:
production

월요일    490
화요일    470
수요일    485
목요일    530
금요일    510
dtype: int64

In [45]:
equipment_data = {       #key 값이 컬럼
    'equipment_id': ['INJ-001', 'INJ-002', 'PRESS-001', 'PRESS-002', 'ASM-001'],
    'equipment_name': ['사출기 1호기', '사출기 2호기', '프레스 1호기', '프레스 2호기', '조립라인 1호기'],
    'equipment_type': ['사출기', '사출기', '프레스', '프레스', '조립라인'],
    'location': ['A동 1라인', 'A동 1라인', 'A동 2라인', 'A동 2라인', 'B동 1라인'],
    'rated_capacity': [150, 150, 200, 200, 100],
    'status': ['ACTIVE', 'ACTIVE', 'ACTIVE', 'ACTIVE', 'ACTIVE']
}

In [47]:
equipment_data

{'equipment_id': ['INJ-001', 'INJ-002', 'PRESS-001', 'PRESS-002', 'ASM-001'],
 'equipment_name': ['사출기 1호기', '사출기 2호기', '프레스 1호기', '프레스 2호기', '조립라인 1호기'],
 'equipment_type': ['사출기', '사출기', '프레스', '프레스', '조립라인'],
 'location': ['A동 1라인', 'A동 1라인', 'A동 2라인', 'A동 2라인', 'B동 1라인'],
 'rated_capacity': [150, 150, 200, 200, 100],
 'status': ['ACTIVE', 'ACTIVE', 'ACTIVE', 'ACTIVE', 'ACTIVE']}

In [46]:
#판다스에서 2차원을 DataFrame이라고 부른다

In [51]:
pd.DataFrame(data=equipment_data) #index,values,columns (구분 잘하기)

  equipment_id equipment_name equipment_type location  rated_capacity  status
0      INJ-001        사출기 1호기            사출기   A동 1라인             150  ACTIVE
1      INJ-002        사출기 2호기            사출기   A동 1라인             150  ACTIVE
2    PRESS-001        프레스 1호기            프레스   A동 2라인             200  ACTIVE
3    PRESS-002        프레스 2호기            프레스   A동 2라인             200  ACTIVE
4      ASM-001       조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [52]:
df=pd.DataFrame(data=equipment_data)

In [53]:
df

  equipment_id equipment_name equipment_type location  rated_capacity  status
0      INJ-001        사출기 1호기            사출기   A동 1라인             150  ACTIVE
1      INJ-002        사출기 2호기            사출기   A동 1라인             150  ACTIVE
2    PRESS-001        프레스 1호기            프레스   A동 2라인             200  ACTIVE
3    PRESS-002        프레스 2호기            프레스   A동 2라인             200  ACTIVE
4      ASM-001       조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [55]:
df=df.set_index('equipment_id')

In [56]:
df

             equipment_name equipment_type location  rated_capacity  status
equipment_id
INJ-001             사출기 1호기            사출기   A동 1라인             150  ACTIVE
INJ-002             사출기 2호기            사출기   A동 1라인             150  ACTIVE
PRESS-001           프레스 1호기            프레스   A동 2라인             200  ACTIVE
PRESS-002           프레스 2호기            프레스   A동 2라인             200  ACTIVE
ASM-001            조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [57]:
df.index

Index(['INJ-001', 'INJ-002', 'PRESS-001', 'PRESS-002', 'ASM-001'], dtype='object', name='equipment_id')

In [58]:
df.columns

Index(['equipment_name', 'equipment_type', 'location', 'rated_capacity',
       'status'],
      dtype='object')

In [59]:
df.values

array([['사출기 1호기', '사출기', 'A동 1라인', 150, 'ACTIVE'],
       ['사출기 2호기', '사출기', 'A동 1라인', 150, 'ACTIVE'],
       ['프레스 1호기', '프레스', 'A동 2라인', 200, 'ACTIVE'],
       ['프레스 2호기', '프레스', 'A동 2라인', 200, 'ACTIVE'],
       ['조립라인 1호기', '조립라인', 'B동 1라인', 100, 'ACTIVE']], dtype=object)

In [60]:
df.ndim

2

In [61]:
df.shape

(5, 5)

In [62]:
df.size

25

In [63]:
df

             equipment_name equipment_type location  rated_capacity  status
equipment_id
INJ-001             사출기 1호기            사출기   A동 1라인             150  ACTIVE
INJ-002             사출기 2호기            사출기   A동 1라인             150  ACTIVE
PRESS-001           프레스 1호기            프레스   A동 2라인             200  ACTIVE
PRESS-002           프레스 2호기            프레스   A동 2라인             200  ACTIVE
ASM-001            조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [65]:
df.describe()  #숫자데이터만 적용됨

       rated_capacity
count        5.000000
mean       160.000000
std         41.833001
min        100.000000
25%        150.000000
50%        150.000000
75%        200.000000
max        200.000000

In [67]:
df.describe(include='all') # 문자열도 포함해서 보여주는 것

       equipment_name equipment_type location  rated_capacity  status
count               5              5        5        5.000000       5
unique              5              3        3             NaN       1
top           사출기 1호기            사출기   A동 1라인             NaN  ACTIVE
freq                1              2        2             NaN       5
mean              NaN            NaN      NaN      160.000000     NaN
std               NaN            NaN      NaN       41.833001     NaN
min               NaN            NaN      NaN      100.000000     NaN
25%               NaN            NaN      NaN      150.000000     NaN
50%               NaN            NaN      NaN      150.000000     NaN
75%               NaN            NaN      NaN      200.000000     NaN
max               NaN            NaN      NaN      200.000000     NaN

In [73]:
df.describe(include='all')['location']['unique']  #따로 데이터를 저장할 수 도 있음

3

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, INJ-001 to ASM-001
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   equipment_name  5 non-null      object
 1   equipment_type  5 non-null      object
 2   location        5 non-null      object
 3   rated_capacity  5 non-null      int64
 4   status          5 non-null      object
dtypes: int64(1), object(4)
memory usage: 240.0+ bytes

In [76]:
#dataframe에서 데이터를 가져오는 방법
# 3가지 방법
# 1. 컬럼 데이터 가져오기
# 2. .loc[,] 로 가져오기
# 3. .iloc[,] 로 가져오기

In [78]:
df

             equipment_name equipment_type location  rated_capacity  status
equipment_id
INJ-001             사출기 1호기            사출기   A동 1라인             150  ACTIVE
INJ-002             사출기 2호기            사출기   A동 1라인             150  ACTIVE
PRESS-001           프레스 1호기            프레스   A동 2라인             200  ACTIVE
PRESS-002           프레스 2호기            프레스   A동 2라인             200  ACTIVE
ASM-001            조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [90]:
df['equipment_name'] #인덱스와 함께 equipment_name이 가져와짐 (바로 대괄호는 colmn을 선택할때)

equipment_id
INJ-001       사출기 1호기
INJ-002       사출기 2호기
PRESS-001     프레스 1호기
PRESS-002     프레스 2호기
ASM-001      조립라인 1호기
Name: equipment_name, dtype: object

In [91]:
df[['equipment_name','rated_capacity']]

             equipment_name  rated_capacity
equipment_id
INJ-001             사출기 1호기             150
INJ-002             사출기 2호기             150
PRESS-001           프레스 1호기             200
PRESS-002           프레스 2호기             200
ASM-001            조립라인 1호기             100

In [92]:
df[['equipment_name' ,'location', 'rated_capacity']]  # [:]은 안됨

             equipment_name location  rated_capacity
equipment_id
INJ-001             사출기 1호기   A동 1라인             150
INJ-002             사출기 2호기   A동 1라인             150
PRESS-001           프레스 1호기   A동 2라인             200
PRESS-002           프레스 2호기   A동 2라인             200
ASM-001            조립라인 1호기   B동 1라인             100

In [93]:
df

             equipment_name equipment_type location  rated_capacity  status
equipment_id
INJ-001             사출기 1호기            사출기   A동 1라인             150  ACTIVE
INJ-002             사출기 2호기            사출기   A동 1라인             150  ACTIVE
PRESS-001           프레스 1호기            프레스   A동 2라인             200  ACTIVE
PRESS-002           프레스 2호기            프레스   A동 2라인             200  ACTIVE
ASM-001            조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [98]:
df.loc['INJ-002',:] #loc는 index와 colmn으로 데이터 가져오는 방식

equipment_name    사출기 2호기
equipment_type        사출기
location           A동 1라인
rated_capacity        150
status             ACTIVE
Name: INJ-002, dtype: object

In [103]:
df.loc['INJ-002':'PRESS-001',:]

             equipment_name equipment_type location  rated_capacity  status
equipment_id
INJ-002             사출기 2호기            사출기   A동 1라인             150  ACTIVE
PRESS-001           프레스 1호기            프레스   A동 2라인             200  ACTIVE

In [104]:
df.loc[:,'equipment_type':'rated_capacity']

             equipment_type location  rated_capacity
equipment_id
INJ-001                 사출기   A동 1라인             150
INJ-002                 사출기   A동 1라인             150
PRESS-001               프레스   A동 2라인             200
PRESS-002               프레스   A동 2라인             200
ASM-001                조립라인   B동 1라인             100

In [107]:
df[['equipment_type','location']].loc['INJ-002':'PRESS-002',:]

             equipment_type location
equipment_id
INJ-002                 사출기   A동 1라인
PRESS-001               프레스   A동 2라인
PRESS-002               프레스   A동 2라인

In [108]:
df

             equipment_name equipment_type location  rated_capacity  status
equipment_id
INJ-001             사출기 1호기            사출기   A동 1라인             150  ACTIVE
INJ-002             사출기 2호기            사출기   A동 1라인             150  ACTIVE
PRESS-001           프레스 1호기            프레스   A동 2라인             200  ACTIVE
PRESS-002           프레스 2호기            프레스   A동 2라인             200  ACTIVE
ASM-001            조립라인 1호기           조립라인   B동 1라인             100  ACTIVE

In [112]:
df.iloc[1:4,1:4] #iloc는 숫자로 인덱스 판별

             equipment_type location  rated_capacity
equipment_id
INJ-002                 사출기   A동 1라인             150
PRESS-001               프레스   A동 2라인             200
PRESS-002               프레스   A동 2라인             200

In [4]:
import pandas as pd

In [11]:
### 파일 읽는 법###

In [6]:
df=pd.read_csv('./data/01_equipment.csv')

In [7]:
df

,equipment_id,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at
0,INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
1,INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
2,PRESS-001,프레스 1호기,프레스,A동 2라인,200.0,2019-05-10,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
3,PRESS-002,프레스 2호기,프레스,A동 2라인,200.0,2022-08-25,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
4,ASM-001,조립라인 1호기,조립라인,B동 1라인,100.0,2020-11-30,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00

In [8]:
pd.read_csv('./data/02_product.csv')

,product_code,product_name,specification,unit,standard_cycle_time,target_quality_rate,upper_spec_limit,lower_spec_limit,created_at,updated_at
0,BUMPER-A,범퍼,1200x300x150mm,EA,75.0,98.5,305.0,295.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1,DOOR-B,도어패널,800x600x50mm,EA,65.0,99.0,605.0,595.0,2024-01-01 00:00:00,2024-01-01 00:00:00
2,DASH-C,대시보드,1000x400x80mm,EA,85.0,98.0,405.0,395.0,2024-01-01 00:00:00,2024-01-01 00:00:00

In [9]:
df.head()

,equipment_id,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at
0,INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
1,INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
2,PRESS-001,프레스 1호기,프레스,A동 2라인,200.0,2019-05-10,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
3,PRESS-002,프레스 2호기,프레스,A동 2라인,200.0,2022-08-25,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
4,ASM-001,조립라인 1호기,조립라인,B동 1라인,100.0,2020-11-30,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00

In [10]:
df.tail()

,equipment_id,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at
0,INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
1,INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
2,PRESS-001,프레스 1호기,프레스,A동 2라인,200.0,2019-05-10,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
3,PRESS-002,프레스 2호기,프레스,A동 2라인,200.0,2022-08-25,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
4,ASM-001,조립라인 1호기,조립라인,B동 1라인,100.0,2020-11-30,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   equipment_id       5 non-null      object
 1   equipment_name     5 non-null      object
 2   equipment_type     5 non-null      object
 3   location           5 non-null      object
 4   rated_capacity     5 non-null      float64
 5   installation_date  5 non-null      object
 6   status             5 non-null      object
 7   created_at         5 non-null      object
 8   updated_at         5 non-null      object
dtypes: float64(1), object(8)
memory usage: 488.0+ bytes

In [15]:
pd.read_csv('./data/01_equipment.csv')

,equipment_id,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at
0,INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
1,INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
2,PRESS-001,프레스 1호기,프레스,A동 2라인,200.0,2019-05-10,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
3,PRESS-002,프레스 2호기,프레스,A동 2라인,200.0,2022-08-25,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
4,ASM-001,조립라인 1호기,조립라인,B동 1라인,100.0,2020-11-30,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00

In [16]:
pd.read_csv('./data/01_equipment.csv',index_col='equipment_id')

,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at
equipment_id,,,,,,,,
INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
PRESS-001,프레스 1호기,프레스,A동 2라인,200.0,2019-05-10,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
PRESS-002,프레스 2호기,프레스,A동 2라인,200.0,2022-08-25,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
ASM-001,조립라인 1호기,조립라인,B동 1라인,100.0,2020-11-30,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00

In [19]:
df=pd.read_csv('./data/05_production.csv')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   production_id    1872 non-null   int64
 1   equipment_id     1872 non-null   object
 2   product_code     1872 non-null   object
 3   production_date  1872 non-null   object
 4   start_time       1872 non-null   object
 5   end_time         1872 non-null   object
 6   target_quantity  1872 non-null   int64
 7   actual_quantity  1872 non-null   int64
 8   good_quantity    1872 non-null   int64
 9   defect_quantity  1872 non-null   int64
 10  cycle_time       1872 non-null   float64
 11  work_order_no    1872 non-null   object
 12  lot_no           1872 non-null   object
 13  operator_id      1872 non-null   object
 14  shift            1872 non-null   object
 15  created_at       1872 non-null   object
 16  updated_at       1872 non-null   object
dtypes: float64(1), int64(5), object(11)
memory usage: 248.8+ KB

In [ ]:
#날짜 텍스트 파일 -> 숫자데이터로 만들기

In [25]:
df=pd.read_csv('./data/05_production.csv',parse_dates = ['production_date','start_time','end_time','created_at','updated_at'])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   production_id    1872 non-null   int64
 1   equipment_id     1872 non-null   object
 2   product_code     1872 non-null   object
 3   production_date  1872 non-null   datetime64[ns]
 4   start_time       1872 non-null   datetime64[ns]
 5   end_time         1872 non-null   datetime64[ns]
 6   target_quantity  1872 non-null   int64
 7   actual_quantity  1872 non-null   int64
 8   good_quantity    1872 non-null   int64
 9   defect_quantity  1872 non-null   int64
 10  cycle_time       1872 non-null   float64
 11  work_order_no    1872 non-null   object
 12  lot_no           1872 non-null   object
 13  operator_id      1872 non-null   object
 14  shift            1872 non-null   object
 15  created_at       1872 non-null   datetime64[ns]
 16  updated_at       1872 non-null   datetime64[ns]
dtypes: datetime64[ns](5), float64(1), int64(5), object(6)
memory usage: 248.8+ KB

In [28]:
#필요한 컬럼만 불러오기

In [30]:
df.columns # 타이핑하지 말고 복붙하는 법

Index(['production_id', 'equipment_id', 'product_code', 'production_date',
       'start_time', 'end_time', 'target_quantity', 'actual_quantity',
       'good_quantity', 'defect_quantity', 'cycle_time', 'work_order_no',
       'lot_no', 'operator_id', 'shift', 'created_at', 'updated_at'],
      dtype='object')

In [32]:
pd.read_csv('./data/05_production.csv',
           usecols= ['production_id','equipment_id','product_code','actual_quantity','production_date','good_quantity','defect_quantity'])

,production_id,equipment_id,product_code,production_date,actual_quantity,good_quantity,defect_quantity
0,1,INJ-001,BUMPER-A,2024-01-01,81,77,4
1,2,INJ-001,BUMPER-A,2024-01-01,78,72,6
2,3,INJ-002,BUMPER-A,2024-01-01,135,132,3
3,4,INJ-002,DASH-C,2024-01-01,92,90,2
4,5,INJ-002,DOOR-B,2024-01-01,129,122,7
...,...,...,...,...,...,...,...
1867,1868,PRESS-002,BUMPER-A,2024-03-31,144,119,25
1868,1869,PRESS-002,DASH-C,2024-03-31,130,109,21
1869,1870,PRESS-002,BUMPER-A,2024-03-31,80,66,14
1870,1871,ASM-001,BUMPER-A,2024-03-31,121,101,20
1871,1872,ASM-001,DOOR-B,2024-03-31,90,74,16

In [34]:
#데이터 타입 지정해서 읽기

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   production_id    1872 non-null   int64
 1   equipment_id     1872 non-null   object
 2   product_code     1872 non-null   object
 3   production_date  1872 non-null   datetime64[ns]
 4   start_time       1872 non-null   datetime64[ns]
 5   end_time         1872 non-null   datetime64[ns]
 6   target_quantity  1872 non-null   int64
 7   actual_quantity  1872 non-null   int64
 8   good_quantity    1872 non-null   int64
 9   defect_quantity  1872 non-null   int64
 10  cycle_time       1872 non-null   float64
 11  work_order_no    1872 non-null   object
 12  lot_no           1872 non-null   object
 13  operator_id      1872 non-null   object
 14  shift            1872 non-null   object
 15  created_at       1872 non-null   datetime64[ns]
 16  updated_at       1872 non-null   datetime64[ns]
dtypes: datetime64[ns](5), float64(1), int64(5), object(6)
memory usage: 248.8+ KB

In [36]:
df.head()

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,81.99,WO202401018359,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,96.87,WO202401016574,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
4,5,INJ-002,DOOR-B,2024-01-01,2024-01-01 20:48:00,2024-01-01 23:12:13,123,129,122,7,67.08,WO202401012674,LOT2024010100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [38]:
df2=pd.read_csv('./data/05_production.csv',dtype={'equipment_id':'category', 'product_code':'category'})

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   production_id    1872 non-null   int64
 1   equipment_id     1872 non-null   category
 2   product_code     1872 non-null   category
 3   production_date  1872 non-null   object
 4   start_time       1872 non-null   object
 5   end_time         1872 non-null   object
 6   target_quantity  1872 non-null   int64
 7   actual_quantity  1872 non-null   int64
 8   good_quantity    1872 non-null   int64
 9   defect_quantity  1872 non-null   int64
 10  cycle_time       1872 non-null   float64
 11  work_order_no    1872 non-null   object
 12  lot_no           1872 non-null   object
 13  operator_id      1872 non-null   object
 14  shift            1872 non-null   object
 15  created_at       1872 non-null   object
 16  updated_at       1872 non-null   object
dtypes: category(2), float64(1), int64(5), object(9)
memory usage: 223.4+ KB