# 04. Pandas 데이터 결합 - 실습 문제

## 실습 안내
- 총 10개 문제
- concat, merge를 활용한 다중 테이블 결합
- 실제 제조 데이터 통합 분석 시나리오
- 생산/품질/설비/정비 데이터 종합 활용

## 데이터 로드

In [1]:
import pandas as pd
import numpy as np

# 데이터 불러오기
production_df = pd.read_csv('../data/05_production.csv', encoding='utf-8-sig')
quality_df = pd.read_csv('../data/07_quality_inspection.csv', encoding='utf-8-sig', na_values=['\\N'])
equipment_df = pd.read_csv('../data/01_equipment.csv', encoding='utf-8-sig')
sensor_df = pd.read_csv('../data/08_sensor_data.csv', encoding='utf-8-sig')
maintenance_df = pd.read_csv('../data/10_maintenance_history.csv', encoding='utf-8-sig')
operation_df = pd.read_csv('../data/06_equipment_operation.csv', encoding='utf-8-sig')
product_df = pd.read_csv('../data/02_product.csv', encoding='utf-8-sig')

# 기본 전처리
production_df['production_date'] = pd.to_datetime(production_df['production_date'])
quality_df['inspection_time'] = pd.to_datetime(quality_df['inspection_time'])

print("데이터 로드 완료!")
print(f"생산: {len(production_df):,}건")
print(f"품질: {len(quality_df):,}건")
print(f"설비: {len(equipment_df):,}건")
print(f"센서: {len(sensor_df):,}건")
print(f"정비: {len(maintenance_df):,}건")
print(f"설비운영: {len(operation_df):,}건")
print(f"제품: {len(product_df):,}건")

데이터 로드 완료!
생산: 1,872건
품질: 37,417건
설비: 5건
센서: 10,920건
정비: 98건
설비운영: 3,304건
제품: 3건

---
## 문제 1: 생산 데이터에 설비 정보 추가

**시나리오**: 생산 데이터에 설비의 상세 정보를 결합하여 분석을 용이하게 하세요.

**요구사항**:
1. production_df와 equipment_df를 equipment_id로 결합 (left join)
2. 필요한 컬럼만 선택:
   - equipment_df에서: equipment_name, equipment_type, manufacturer, capacity
3. 결합된 데이터의 처음 10개 행 출력
4. 결합 전후 데이터 건수 확인

**힌트**: `pd.merge()`, how='left', on='equipment_id'

In [6]:
production_eq=pd.merge(production_df,equipment_df,on='equipment_id',how='left')

In [4]:
equipment_df.head(2)

,equipment_id,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at
0,INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00
1,INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00

In [19]:
equipment_df.loc[:,['equipment_name','equipment_type','rated_capacity']]

  equipment_name equipment_type  rated_capacity
0        사출기 1호기            사출기           150.0
1        사출기 2호기            사출기           150.0
2        프레스 1호기            프레스           200.0
3        프레스 2호기            프레스           200.0
4       조립라인 1호기           조립라인           100.0

In [10]:
production_eq.drop(columns=['location','installation_date','status'],inplace= True) # columns 삭제

KeyError: "['location', 'installation_date', 'status'] not found in axis"

In [11]:
production_eq

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,...,lot_no,operator_id,shift,created_at_x,updated_at_x,equipment_name,equipment_type,rated_capacity,created_at_y,updated_at_y
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,...,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,사출기 1호기,사출기,150.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,...,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,사출기 1호기,사출기,150.0,2024-01-01 00:00:00,2024-01-01 00:00:00
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,...,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,사출기 2호기,사출기,150.0,2024-01-01 00:00:00,2024-01-01 00:00:00
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,...,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,사출기 2호기,사출기,150.0,2024-01-01 00:00:00,2024-01-01 00:00:00
4,5,INJ-002,DOOR-B,2024-01-01,2024-01-01 20:48:00,2024-01-01 23:12:13,123,129,122,7,...,LOT2024010100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,사출기 2호기,사출기,150.0,2024-01-01 00:00:00,2024-01-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,1868,PRESS-002,BUMPER-A,2024-03-31,2024-03-31 20:19:00,2024-03-31 23:25:19,150,144,119,25,...,LOT2024033100210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,프레스 2호기,프레스,200.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1868,1869,PRESS-002,DASH-C,2024-03-31,2024-04-01 00:15:00,2024-04-01 02:59:58,136,130,109,21,...,LOT2024033100211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,프레스 2호기,프레스,200.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1869,1870,PRESS-002,BUMPER-A,2024-03-31,2024-04-01 05:53:00,2024-04-01 07:26:15,84,80,66,14,...,LOT2024033100212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,프레스 2호기,프레스,200.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1870,1871,ASM-001,BUMPER-A,2024-03-31,2024-03-31 10:24:00,2024-03-31 13:25:41,143,121,101,20,...,LOT2024033100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,조립라인 1호기,조립라인,100.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1871,1872,ASM-001,DOOR-B,2024-03-31,2024-03-31 20:14:00,2024-03-31 22:16:42,106,90,74,16,...,LOT2024033100110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,조립라인 1호기,조립라인,100.0,2024-01-01 00:00:00,2024-01-01 00:00:00

---
## 문제 2: 생산 데이터에 제품 정보 추가

**시나리오**: 생산 데이터에 제품 상세 정보를 결합하세요.

**요구사항**:
1. production_df와 product_df를 product_code로 결합 (left join)
2. 제품명(product_name), 카테고리(category) 추가
3. 카테고리별 생산 건수 집계
4. 카테고리별 평균 불량률 계산 (defect_quantity / actual_quantity)

**힌트**: merge 후 groupby로 집계

In [13]:
# 여기에 코드 작성
pd.merge(production_df,product_df,on='product_code',how='left').head(2)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,...,updated_at_x,product_name,specification,unit,standard_cycle_time,target_quality_rate,upper_spec_limit,lower_spec_limit,created_at_y,updated_at_y
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,...,2026-01-30 00:42:48,범퍼,1200x300x150mm,EA,75.0,98.5,305.0,295.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,...,2026-01-30 00:42:48,범퍼,1200x300x150mm,EA,75.0,98.5,305.0,295.0,2024-01-01 00:00:00,2024-01-01 00:00:00

In [14]:

comb2=pd.merge(production_df,product_df,on='product_code',how='left')

In [ ]:
##갯수 세는 두가지 방법!
comb2.groupby('product_name')['production_id'].count()

product_name
대시보드    583
도어패널    641
범퍼      648
Name: production_id, dtype: int64

In [16]:
comb2['product_name'].value_counts()

product_name
범퍼      648
도어패널    641
대시보드    583
Name: count, dtype: int64

In [17]:
import numpy as np

In [18]:
comb2['불량률']=(comb2['defect_quantity']/comb2['actual_quantity']*100).replace([np.inf,-np.inf], 0)

In [19]:
comb2.groupby('product_name').agg({'production_id':'size',
                                   '불량률':'mean'})

              production_id        불량률
product_name
대시보드                    583  10.121749
도어패널                    641  10.159205
범퍼                      648  10.376804

---
## 문제 3: 생산 데이터와 품질 검사 결합

**시나리오**: 각 생산 건에 대한 품질 검사 정보를 결합하세요.

**요구사항**:
1. production_df와 quality_df를 production_id로 결합 (left join)
2. 결합 후 데이터 건수 확인 (1:N 관계 주의)
3. production_id별 검사 건수 계산
4. 검사가 없는 생산 건 찾기

**힌트**: left join, 결합 후 value_counts(), isna() 확인

In [22]:
# 여기에 코드 작성
comb3=pd.merge(production_df,quality_df,on = 'production_id' , how = 'left')

In [23]:
comb3.shape

(37417, 31)

In [24]:
comb3.head(2)

,production_id,equipment_id_x,product_code_x,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,...,inspection_type,result,defect_code,measurement_value,measurement_unit,inspector_id,lot_no_y,sample_size,notes,created_at_y
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,...,FINAL,PASS,NaN,300.8279,mm,OP007,LOT2024010100101,1,NaN,2026-01-30 01:24:59
1,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,...,FINAL,PASS,NaN,299.7696,mm,OP008,LOT2024010100101,1,NaN,2026-01-30 01:24:59

In [ ]:
comb3.groupby('production_id').size()  #groupby에서 데이터 갯수 세는 법

production_id
1       11
2       13
3       13
4       11
5       17
        ..
1868    35
1869    31
1870    20
1871    30
1872    23
Length: 1872, dtype: int64

In [ ]:
comb3['production_id'].value_counts() # 특정 데이터 갯수 세는 다른 방법

production_id
1288    36
1346    35
1868    35
1504    35
1188    35
        ..
711      9
296      9
149      9
718      9
856      9
Name: count, Length: 1872, dtype: int64

In [ ]:
production_df['production_id'].isin(quality_df['production_id']) # 호환하고 있는것만 가져오는 방법 (품질팀에 id없으면 검사 안한 것)

0       True
1       True
2       True
3       True
4       True
        ...
1867    True
1868    True
1869    True
1870    True
1871    True
Name: production_id, Length: 1872, dtype: bool

---
## 문제 4: 품질 검사 데이터 집계 후 생산 데이터와 결합

**시나리오**: production_id별 품질 검사 결과를 집계한 후 생산 데이터에 추가하세요.

**요구사항**:
1. quality_df를 production_id로 그룹화하여 집계:
   - 검사 건수
   - 불량 건수 (result='FAIL')
   - 평균 측정값
2. 집계 결과를 production_df와 결합 (left join)
3. 검사가 없는 경우 0으로 채우기
4. 처음 10개 행 출력

**힌트**: groupby + agg, reset_index(), merge, fillna(0)

In [29]:
quality_df.head(2)

,inspection_id,production_id,equipment_id,product_code,inspection_time,inspection_type,result,defect_code,measurement_value,measurement_unit,inspector_id,lot_no,sample_size,notes,created_at
0,1,1,INJ-001,BUMPER-A,2024-01-01 09:41:18,FINAL,PASS,NaN,300.8279,mm,OP007,LOT2024010100101,1,NaN,2026-01-30 01:24:59
1,2,1,INJ-001,BUMPER-A,2024-01-01 08:17:24,FINAL,PASS,NaN,299.7696,mm,OP008,LOT2024010100101,1,NaN,2026-01-30 01:24:59

In [30]:
product_df.head(2)

,product_code,product_name,specification,unit,standard_cycle_time,target_quality_rate,upper_spec_limit,lower_spec_limit,created_at,updated_at
0,BUMPER-A,범퍼,1200x300x150mm,EA,75.0,98.5,305.0,295.0,2024-01-01 00:00:00,2024-01-01 00:00:00
1,DOOR-B,도어패널,800x600x50mm,EA,65.0,99.0,605.0,595.0,2024-01-01 00:00:00,2024-01-01 00:00:00

In [41]:
def fail_len(x):
    return (x=='FAIL').sum()

In [43]:
quality_summary=quality_df.groupby('production_id').agg({'inspection_id':'count',
                                         'result': fail_len,
                                         'measurement_value': 'mean'})
#함수를 사용해서 return 하는 법

In [45]:
quality_summary.columns = ['검사건수','불량건수','평균측정값']

In [46]:
comb4=pd.merge(production_df,quality_summary,on='production_id',how = 'left')

---
## 문제 5: 설비 + 생산 + 정비 종합 분석

**시나리오**: 설비별 생산 실적과 정비 이력을 종합하여 설비 성능을 평가하세요.

**요구사항**:
1. production_df를 설비별로 집계:
   - 생산 건수, 총 생산량
2. maintenance_df를 설비별로 집계:
   - 정비 건수, 총 정비 비용, 총 정지 시간
3. equipment_df에 위 두 집계 결과를 순차적으로 결합 (left join)
4. 결측치는 0으로 채우기
5. 설비당 평균 정비 비용 계산

**힌트**: 각각 집계 후 reset_index(), 순차적 merge

In [47]:
production_df.head(2)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [49]:
# 여기에 코드 작성 왜 설비별로 집게 하는지 -> 중복데이터 제거를 위해서
production_summary=production_df.groupby('equipment_id').agg({'production_id':'count',
                                            'actual_quantity': 'sum'})

In [58]:
production_summary.columns=['생산 건수', '총 생산량']

In [56]:
maintenance_df.head(2)

,equipment_id,maintenance_type,start_time,end_time,maintenance_description,parts_replaced,cost,technician_id,downtime_hours,notes,created_at
0,INJ-002,PREVENTIVE,2024-01-03 10:06:38,2024-01-03 11:38:28,월간 정기점검,NaN,1597990.91,OP015,1.53,다음 정비 시 추가 점검 요망,2026-01-30 02:23:22.393125
1,INJ-002,PREVENTIVE,2024-01-05 15:47:52,2024-01-05 17:47:18,정기 윤활유 교환,"금형, 압력센서",2488706.64,OP011,1.99,NaN,2026-01-30 02:23:22.396196

In [55]:
maintenance_summary=maintenance_df.groupby('equipment_id').agg({'equipment_id':'count',
                                            'cost': 'sum',
                                            'downtime_hours':'sum' })

In [57]:
maintenance_summary.columns=['정비건수', '총정비비용', '총정지시간']

In [64]:
comb5=pd.merge(equipment_df,production_summary,on='equipment_id',how='left')

In [65]:
comb5=pd.merge(comb5,maintenance_summary,on='equipment_id',how='left')

In [66]:
comb5

,equipment_id,equipment_name,equipment_type,location,rated_capacity,installation_date,status,created_at,updated_at,생산 건수,총 생산량,정비건수,총정비비용,총정지시간
0,INJ-001,사출기 1호기,사출기,A동 1라인,150.0,2020-03-15,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00,262,28163,17,45291758.85,27.85
1,INJ-002,사출기 2호기,사출기,A동 1라인,150.0,2021-06-20,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00,430,51958,23,75076538.50,40.36
2,PRESS-001,프레스 1호기,프레스,A동 2라인,200.0,2019-05-10,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00,468,52069,18,44564270.41,29.69
3,PRESS-002,프레스 2호기,프레스,A동 2라인,200.0,2022-08-25,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00,478,51929,21,70921381.60,37.71
4,ASM-001,조립라인 1호기,조립라인,B동 1라인,100.0,2020-11-30,ACTIVE,2024-01-01 00:00:00,2024-01-01 00:00:00,234,22485,19,60072924.01,30.79

---
## 문제 6: 생산량과 설비 capacity 비교

**시나리오**: 설비의 capacity 대비 실제 생산량을 비교하여 가동률을 분석하세요.

**요구사항**:
1. production_df와 equipment_df를 결합 (설비 정보 추가)
2. 각 생산 건의 capacity 대비 생산량 비율 계산:
   - capacity_utilization = (actual_quantity / capacity) * 100
3. 설비별 평균 capacity_utilization 계산
4. 가동률이 가장 높은 상위 5개 설비 출력

**힌트**: merge, 새 컬럼 생성, groupby, sort_values()

In [67]:
# 여기에 코드 작성
production_df.columns

Index(['production_id', 'equipment_id', 'product_code', 'production_date',
       'start_time', 'end_time', 'target_quantity', 'actual_quantity',
       'good_quantity', 'defect_quantity', 'cycle_time', 'work_order_no',
       'lot_no', 'operator_id', 'shift', 'created_at', 'updated_at'],
      dtype='object')

In [68]:
equipment_df.columns

Index(['equipment_id', 'equipment_name', 'equipment_type', 'location',
       'rated_capacity', 'installation_date', 'status', 'created_at',
       'updated_at'],
      dtype='object')

In [75]:
comb6=pd.merge(production_df,equipment_df,on = 'equipment_id', how = 'left')

In [77]:
comb6['가동률']=comb6['actual_quantity']/com6['rated_capacity']*100

In [78]:
comb6.groupby('equipment_id')['가동률'].mean().sort_values(ascending=False)

equipment_id
ASM-001      96.089744
INJ-002      80.555039
INJ-001      71.661578
PRESS-001    55.629274
PRESS-002    54.319038
Name: 가동률, dtype: float64

---
## 문제 7: 제조사별 설비 성능 분석

**시나리오**: 설비 제조사별로 생산 성능을 비교 분석하세요.

**요구사항**:
1. production_df에 equipment_df를 결합 (manufacturer 정보 추가)
2. 제조사별로 다음 집계:
   - 설비 수 (equipment_id의 unique count)
   - 총 생산량
   - 평균 불량률
   - 평균 사이클 타임
3. 총 생산량 기준 내림차순 정렬

**힌트**: merge, groupby with nunique, agg

In [ ]:
# 여기에 코드 작성

---
## 문제 8: 월별 데이터 분할 후 재결합

**시나리오**: 생산 데이터를 월별로 분할하여 각각 분석한 후 다시 합치세요.

**요구사항**:
1. production_df를 1월, 2월, 3월 데이터로 분할
2. 각 월의 데이터에 '분기' 컬럼 추가 (모두 'Q1')
3. concat으로 세 DataFrame을 세로로 결합
4. 결합 후 인덱스 재설정 (ignore_index=True)
5. 분기별 생산 건수 확인

**힌트**: 월별 필터링, concat([df1, df2, df3], axis=0)

In [79]:
# 여기에 코드 작성
production_df.head(2)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [80]:
production_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1872 entries, 0 to 1871
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   production_id    1872 non-null   int64
 1   equipment_id     1872 non-null   object
 2   product_code     1872 non-null   object
 3   production_date  1872 non-null   datetime64[ns]
 4   start_time       1872 non-null   object
 5   end_time         1872 non-null   object
 6   target_quantity  1872 non-null   int64
 7   actual_quantity  1872 non-null   int64
 8   good_quantity    1872 non-null   int64
 9   defect_quantity  1872 non-null   int64
 10  cycle_time       1872 non-null   float64
 11  work_order_no    1872 non-null   object
 12  lot_no           1872 non-null   object
 13  operator_id      1872 non-null   object
 14  shift            1872 non-null   object
 15  created_at       1872 non-null   object
 16  updated_at       1872 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(5), object(10)
memory usage: 248.8+ KB

In [82]:
prod_1=production_df.loc[production_df['production_date'].dt.month==1].copy()

In [83]:
prod_2=production_df.loc[production_df['production_date'].dt.month==2].copy()

In [84]:
prod_3=production_df.loc[production_df['production_date'].dt.month==3].copy()

In [90]:
prod_1['분기'] = 'Q1'

In [91]:
prod_2['분기'] = 'Q1'

In [92]:
prod_3['분기'] = 'Q1'

In [94]:
pd.concat([prod_1,prod_2,prod_3], ignore_index= True)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at,분기
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,81.99,WO202401018359,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,96.87,WO202401016574,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
4,5,INJ-002,DOOR-B,2024-01-01,2024-01-01 20:48:00,2024-01-01 23:12:13,123,129,122,7,67.08,WO202401012674,LOT2024010100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,1868,PRESS-002,BUMPER-A,2024-03-31,2024-03-31 20:19:00,2024-03-31 23:25:19,150,144,119,25,77.63,WO202403317101,LOT2024033100210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
1868,1869,PRESS-002,DASH-C,2024-03-31,2024-04-01 00:15:00,2024-04-01 02:59:58,136,130,109,21,76.15,WO202403318434,LOT2024033100211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
1869,1870,PRESS-002,BUMPER-A,2024-03-31,2024-04-01 05:53:00,2024-04-01 07:26:15,84,80,66,14,69.95,WO202403317294,LOT2024033100212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
1870,1871,ASM-001,BUMPER-A,2024-03-31,2024-03-31 10:24:00,2024-03-31 13:25:41,143,121,101,20,90.10,WO202403317268,LOT2024033100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1
1871,1872,ASM-001,DOOR-B,2024-03-31,2024-03-31 20:14:00,2024-03-31 22:16:42,106,90,74,16,81.80,WO202403318062,LOT2024033100110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,Q1

---
## 문제 9: 생산-품질-설비 3중 결합

**시나리오**: 생산, 품질, 설비 데이터를 모두 결합하여 종합 분석 테이블을 만드세요.

**요구사항**:
1. 품질 데이터를 production_id별로 집계:
   - 검사 건수, 불량 건수, 평균 측정값
2. 생산 데이터에 품질 집계 결합 (left join)
3. 결과에 설비 정보 결합 (equipment_name, equipment_type 추가)
4. 설비 타입별 평균 불량률 계산
5. 결과를 설비 타입으로 그룹화하여 출력

**힌트**: 순차적 merge, 중간 결과 확인하며 진행

In [102]:
# 여기에 코드 작성
def fail(x) :
    return (x=='FAIL').sum()

In [103]:
quality_df.columns

Index(['inspection_id', 'production_id', 'equipment_id', 'product_code',
       'inspection_time', 'inspection_type', 'result', 'defect_code',
       'measurement_value', 'measurement_unit', 'inspector_id', 'lot_no',
       'sample_size', 'notes', 'created_at'],
      dtype='object')

In [107]:
quality_summary1=quality_df.groupby('production_id').agg({'production_id': 'count',
                                         'result' : fail,
                                         'measurement_value':'mean'})

In [108]:
quality_summary1.columns=['검사 건수','불량 건수','평균 측정값']

In [109]:
quality_summary1

               검사 건수  불량 건수      평균 측정값
production_id
1                 11      4  300.583600
2                 13      6  299.203377
3                 13      3  298.295115
4                 11      2  400.704636
5                 17      7  598.715941
...              ...    ...         ...
1868              35     25  297.999489
1869              31     21  400.624397
1870              20     14  301.137370
1871              30     20  300.775347
1872              23     16  603.366317

[1872 rows x 3 columns]

In [112]:
eq_df = equipment_df.loc[:,'equipment_id':'equipment_type']

In [114]:
prod_all=pd.merge(production_df, quality_summary1,on = 'production_id', how = 'left')

In [115]:
pd.merge(prod_all,eq_df, on = 'equipment_id', how = 'left')

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,...,lot_no,operator_id,shift,created_at,updated_at,검사 건수,불량 건수,평균 측정값,equipment_name,equipment_type
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,...,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,11,4,300.583600,사출기 1호기,사출기
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,...,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,13,6,299.203377,사출기 1호기,사출기
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,...,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,13,3,298.295115,사출기 2호기,사출기
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,...,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,11,2,400.704636,사출기 2호기,사출기
4,5,INJ-002,DOOR-B,2024-01-01,2024-01-01 20:48:00,2024-01-01 23:12:13,123,129,122,7,...,LOT2024010100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,17,7,598.715941,사출기 2호기,사출기
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,1868,PRESS-002,BUMPER-A,2024-03-31,2024-03-31 20:19:00,2024-03-31 23:25:19,150,144,119,25,...,LOT2024033100210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,35,25,297.999489,프레스 2호기,프레스
1868,1869,PRESS-002,DASH-C,2024-03-31,2024-04-01 00:15:00,2024-04-01 02:59:58,136,130,109,21,...,LOT2024033100211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,31,21,400.624397,프레스 2호기,프레스
1869,1870,PRESS-002,BUMPER-A,2024-03-31,2024-04-01 05:53:00,2024-04-01 07:26:15,84,80,66,14,...,LOT2024033100212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,20,14,301.137370,프레스 2호기,프레스
1870,1871,ASM-001,BUMPER-A,2024-03-31,2024-03-31 10:24:00,2024-03-31 13:25:41,143,121,101,20,...,LOT2024033100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,30,20,300.775347,조립라인 1호기,조립라인
1871,1872,ASM-001,DOOR-B,2024-03-31,2024-03-31 20:14:00,2024-03-31 22:16:42,106,90,74,16,...,LOT2024033100110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,23,16,603.366317,조립라인 1호기,조립라인

---
## 문제 10: 종합 설비 대시보드 데이터 생성

**시나리오**: 모든 데이터를 결합하여 설비별 종합 성능 대시보드를 위한 데이터를 생성하세요.

**요구사항**:
1. 설비별 생산 집계:
   - 생산 건수, 총 생산량, 평균 불량률
2. 설비별 정비 집계:
   - 정비 건수, 총 정비 비용, 평균 정지 시간
3. 설비별 설비운영 집계:
   - RUNNING 시간 합계 (operation_status='RUNNING'인 경우)
4. equipment_df를 기준으로 위 3개 집계를 모두 결합 (left join)
5. 결측치를 0으로 채우기
6. 다음 지표 계산:
   - 가동률 = (RUNNING 시간 / 전체 시간) * 100
   - 생산성 = 총 생산량 / 생산 건수
   - 정비 효율 = 총 생산량 / 정비 건수
7. 종합 점수 = 생산성 * (100 - 평균불량률) / 정비건수
8. 종합 점수 상위 5개 설비 출력

**힌트**: 복잡한 문제. 단계별로 진행, 각 집계 후 reset_index(), 순차적 merge, 계산 컬럼 생성

In [ ]:
# 여기에 코드 작성

---
## 수고하셨습니다!

### 학습 체크리스트
- [ ] concat으로 DataFrame 이어붙이기
- [ ] merge의 다양한 join 타입 이해 (inner, left, right, outer)
- [ ] 1:1, 1:N 관계 이해
- [ ] 집계 후 결합하기
- [ ] 순차적 다중 테이블 결합
- [ ] 결합 후 결측치 처리
- [ ] 복합 분석을 위한 데이터 통합
- [ ] 실무 분석 시나리오 적용